# Generated by Django 5.1.4 on 2025-04-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student', max_length=10),
        ),
    ]
