# Generated by Django 5.1.4 on 2025-04-02 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='checked_papers/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswersOfStudent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('pdf_file', models.FileField(upload_to='checked_papers/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PapersOfProf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.JSONField(default=list)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('change_of_marks', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QueriesOfPaper', to='paper.paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QueriesOfStudent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
