# Generated by Django 5.1.4 on 2025-04-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_answer_paper_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='AnswersOfPaper', to='paper.paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='name',
            field=models.CharField(default='subject', max_length=30),
        ),
    ]
