# Generated by Django 5.1.4 on 2025-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_answer_paper_paper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='questions',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
