# Generated by Django 5.1.4 on 2025-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_section_delete_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='papers',
        ),
        migrations.AddField(
            model_name='paper',
            name='sections',
            field=models.ManyToManyField(related_name='papers_of_section', to='paper.section'),
        ),
    ]
