# Generated by Django 5.1.4 on 2025-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_remove_section_papers_paper_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='change_of_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='identity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
