# Generated by Django 5.1.4 on 2025-04-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_query_marks_alter_query_change_of_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='marks',
        ),
    ]
