# Generated by Django 5.1.4 on 2025-04-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_query_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
