# Generated by Django 5.1.4 on 2025-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0012_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='change_of_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
