# Generated by Django 5.1.4 on 2025-04-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0013_alter_query_change_of_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='subject', max_length=100),
        ),
    ]
